import os

# Edited by Copilot: config probe

EMBEDDING_MODEL = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
EMBEDDING_DEVICE = 'auto'
LLM_MODEL = os.getenv('OLLAMA_MODEL', 'qwen2.5:1.5b')
LLM_TEMPERATURE = 0.7
LLM_TOP_P = 0.9
LLM_REPEAT_PENALTY = 1.1

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 100
CHUNK_SIZE_OPTIONS = [500, 800, 1000, 1500, 2000]
CHUNK_OVERLAP_OPTIONS = [50, 80, 100, 200]

RETRIEVER_K = 10

CONV_MEMORY_K = 3

RERANK_FERCH_K = 20

SUPPORTED_TYPES = ['pdf', 'docx', 'doc']

APP_TITLE = 'ADI'
APP_VERSION = '1.1'
APP_ICON = '📄'

CITATION_TOP_N = 3          
CITATION_PREVIEW_CHARS = 180  
CITATION_HIGHLIGHT_CHARS = 300